/* ==========================================================================
   PRODUCTS CATALOG DATA — 25 SKUs
   Organized under two mega-categories: CP Kids & Adults
   ========================================================================== */

export const MEGA_CATEGORIES = [
  { id: 'all', label: 'All Products' },
  { id: 'cp-kids', label: 'Shop for CP Kids' },
  { id: 'adults', label: 'Shop for Adults' }
];

export const SUB_CATEGORIES = {
  'cp-kids': [
    { id: 'cp-wheelchair', label: 'CP Wheelchairs' },
    { id: 'cp-seating', label: 'CP Seating & Posture' },
    { id: 'cp-orthotics', label: 'CP Orthotics' },
    { id: 'cp-mobility', label: 'CP Mobility Aids' },
    { id: 'cp-therapy', label: 'CP Therapy & Support' }
  ],
  'adults': [
    { id: 'wheelchair', label: 'Wheelchairs' },
    { id: 'cushion', label: 'Seat Cushions' },
    { id: 'insoles', label: 'Foot Insoles' },
    { id: 'pillow', label: 'Neck & Sleep' },
    { id: 'walking', label: 'Walking Aids' }
  ]
};

export const PRODUCTS = [
  /* ===================================================================
     MEGA-CATEGORY: SHOP FOR CP KIDS (12 SKUs)
     =================================================================== */
  {
    id: 'MC-CPW01',
    title: 'Morecare CP Pediatric Power Wheelchair',
    megaCategory: 'cp-kids',
    category: 'cp-wheelchair',
    categoryLabel: 'CP Wheelchairs',
    price: 89999,
    oldPrice: 110000,
    rating: 4.9,
    reviews: 87,
    desc: 'Pediatric motorized wheelchair with adjustable tilt, recline, and elevation. Compact joystick controller designed for small hands with sensitivity adjustment.',
    features: ['Adjustable Tilt & Recline', 'Pediatric Joystick', 'Growth-Adaptable Frame', 'Anti-tip Rear Wheels'],
    sizes: ['Small (10"-12" seat)', 'Medium (14" seat)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="35" cy="72" r="16" stroke-width="3.5"/><circle cx="72" cy="72" r="10" stroke-width="2.5"/><rect x="22" y="28" width="28" height="24" rx="5" fill="currentColor" fill-opacity="0.08"/><path d="M22 42h32M35 72l18-30M25 18h22M72 72l-12-28" stroke-linecap="round"/><circle cx="32" cy="15" r="6" stroke-width="2"/></svg>`
  },
  {
    id: 'MC-CPW02',
    title: 'Morecare CP Tilt-in-Space Manual Chair',
    megaCategory: 'cp-kids',
    category: 'cp-wheelchair',
    categoryLabel: 'CP Wheelchairs',
    price: 45999,
    oldPrice: 55000,
    rating: 4.8,
    reviews: 64,
    desc: 'Manual tilt-in-space wheelchair designed for children with moderate-to-severe CP. Full postural support system with adjustable headrest, thoracic pads, and hip guides.',
    features: ['45° Tilt Range', 'Adjustable Headrest', 'Thoracic Lateral Pads', 'Swing-Away Footrests'],
    sizes: ['Pediatric Small (10" seat)', 'Pediatric Medium (12" seat)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="32" cy="70" r="14" stroke-width="3"/><circle cx="68" cy="70" r="8" stroke-width="2.5"/><path d="M20 25l10-5 8 5v30H20z" fill="currentColor" fill-opacity="0.06"/><path d="M20 50h40M32 70l16-25M68 70l-12-25M25 15h10" stroke-linecap="round"/><rect x="18" y="10" width="14" height="8" rx="4"/></svg>`
  },
  {
    id: 'MC-CPS01',
    title: 'Morecare CP Postural Support Seat Insert',
    megaCategory: 'cp-kids',
    category: 'cp-seating',
    categoryLabel: 'CP Seating & Posture',
    price: 12999,
    oldPrice: 16000,
    rating: 4.7,
    reviews: 132,
    desc: 'Custom-contoured seat insert for strollers and wheelchairs. Dual-density foam with anterior trunk support, hip abduction wedge, and moisture-wicking cover.',
    features: ['Dual-Density Foam Core', 'Hip Abduction Wedge', 'Anterior Trunk Support', 'Washable Liner'],
    sizes: ['Toddler (1-3 yrs)', 'Child (4-8 yrs)', 'Youth (9-14 yrs)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><rect x="20" y="20" width="60" height="60" rx="12" fill="currentColor" fill-opacity="0.06" stroke-width="3"/><path d="M35 30v40M50 25v50M65 30v40" stroke-dasharray="3 3" stroke-opacity="0.3"/><path d="M30 50c10-8 30-8 40 0" stroke-width="2"/><circle cx="50" cy="45" r="8" stroke-dasharray="2 2"/></svg>`
  },
  {
    id: 'MC-CPO01',
    title: 'Morecare CP Ankle-Foot Orthotic Insoles',
    megaCategory: 'cp-kids',
    category: 'cp-orthotics',
    categoryLabel: 'CP Orthotics',
    price: 3499,
    oldPrice: 4500,
    rating: 4.8,
    reviews: 198,
    desc: 'Pediatric AFO-compatible insoles with deep heel cup and medial arch support. Promotes ankle stability and gait correction for children with spastic diplegia.',
    features: ['AFO-Compatible Design', 'Deep Heel Cup', 'Medial Arch Cradle', 'Antimicrobial Top Layer'],
    sizes: ['Toddler (UK 5-8)', 'Child (UK 9-12)', 'Youth (UK 13-3)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M42 12c-8 18-5 32-12 48s6 22 18 22 18-8 18-24-6-30-12-42-4-8-12-4z" stroke-width="3" fill="currentColor" fill-opacity="0.05"/><circle cx="48" cy="68" r="5" stroke-dasharray="2 2"/><path d="M38 48c6 4 14 4 20 0" stroke-width="2"/><path d="M35 30l8-4 8 4" stroke-linecap="round"/></svg>`
  },
  {
    id: 'MC-CPM01',
    title: 'Morecare CP Standing Frame',
    megaCategory: 'cp-kids',
    category: 'cp-mobility',
    categoryLabel: 'CP Mobility Aids',
    price: 34999,
    oldPrice: 42000,
    rating: 4.9,
    reviews: 56,
    desc: 'Supine/prone standing frame with hydraulic lift assist. Promotes bone density, hip development, and respiratory function in non-ambulatory CP children.',
    features: ['Hydraulic Lift Assist', 'Adjustable Knee Blocks', 'Thoracic Chest Pad', 'Tray Table Included'],
    sizes: ['Small (3-6 yrs)', 'Medium (7-12 yrs)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><rect x="30" y="10" width="40" height="80" rx="4" stroke-width="2" stroke-dasharray="4 2"/><circle cx="50" cy="25" r="7" stroke-width="2.5"/><path d="M50 32v30M38 42h24M42 62h16" stroke-linecap="round" stroke-width="2.5"/><rect x="35" y="82" width="12" height="8" rx="2" fill="currentColor" fill-opacity="0.15"/><rect x="53" y="82" width="12" height="8" rx="2" fill="currentColor" fill-opacity="0.15"/></svg>`
  },
  {
    id: 'MC-CPM02',
    title: 'Morecare CP Gait Trainer Walker',
    megaCategory: 'cp-kids',
    category: 'cp-mobility',
    categoryLabel: 'CP Mobility Aids',
    price: 28999,
    oldPrice: 35000,
    rating: 4.7,
    reviews: 73,
    desc: 'Posterior gait trainer with pelvic support harness. Encourages natural gait pattern development while providing trunk stability and partial weight bearing.',
    features: ['Pelvic Support Harness', 'Height-Adjustable Frame', 'Locking Rear Wheels', 'Forearm Grip Supports'],
    sizes: ['Small (75-100 cm)', 'Medium (100-130 cm)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M30 15h40M30 15v55M70 15v55M30 70h40" stroke-linecap="round" stroke-width="2.5"/><circle cx="30" cy="75" r="5" stroke-width="2"/><circle cx="70" cy="75" r="5" stroke-width="2"/><circle cx="50" cy="30" r="6" stroke-width="2"/><path d="M50 36v20M42 46h16" stroke-linecap="round"/></svg>`
  },
  {
    id: 'MC-CPP01',
    title: 'Morecare CP Head & Neck Support Pillow',
    megaCategory: 'cp-kids',
    category: 'cp-therapy',
    categoryLabel: 'CP Therapy & Support',
    price: 2999,
    oldPrice: 3800,
    rating: 4.6,
    reviews: 145,
    desc: 'Contoured pediatric head support with cervical groove. Prevents head drop and lateral tilt during wheelchair use and sleep positioning.',
    features: ['Cervical Groove Design', 'Memory Foam Core', 'Hypoallergenic Cover', 'Universal Wheelchair Mount'],
    sizes: ['Infant (0-2 yrs)', 'Toddler (2-5 yrs)', 'Child (6-12 yrs)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><rect x="18" y="30" width="64" height="40" rx="14" stroke-width="3" fill="currentColor" fill-opacity="0.05"/><path d="M18 50q16-12 32 0t32 0" stroke-width="2"/><circle cx="50" cy="42" r="4" fill="currentColor" fill-opacity="0.2"/></svg>`
  },
  {
    id: 'MC-CPS02',
    title: 'Morecare CP Adaptive Feeding Seat',
    megaCategory: 'cp-kids',
    category: 'cp-seating',
    categoryLabel: 'CP Seating & Posture',
    price: 18999,
    oldPrice: 24000,
    rating: 4.8,
    reviews: 89,
    desc: 'Floor-level adaptive seating system for mealtimes and play. Adjustable back angle, lateral supports, and tray with lip guard for self-feeding development.',
    features: ['Adjustable Back Angle', 'Lateral Trunk Supports', 'Anti-Slip Tray with Lip', 'Non-Marking Rubber Base'],
    sizes: ['Small (1-4 yrs)', 'Large (5-10 yrs)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M25 75h50M25 35l10-15h30l10 15" stroke-linecap="round" stroke-width="2.5"/><rect x="30" y="35" width="40" height="40" rx="6" fill="currentColor" fill-opacity="0.06"/><path d="M20 50h60" stroke-width="2"/><circle cx="50" cy="55" r="5" stroke-dasharray="2 2"/></svg>`
  },
  {
    id: 'MC-CPS03',
    title: 'Morecare CP Abduction Wedge Cushion',
    megaCategory: 'cp-kids',
    category: 'cp-seating',
    categoryLabel: 'CP Seating & Posture',
    price: 4999,
    oldPrice: 6500,
    rating: 4.7,
    reviews: 112,
    desc: 'Triangular abduction wedge cushion for hip positioning. Prevents scissoring in children with adductor spasticity while seated in wheelchair or floor seating.',
    features: ['45° Wedge Angle', 'High-Density Foam', 'Velcro Wheelchair Strap', 'Removable Waterproof Cover'],
    sizes: ['Small (6" height)', 'Medium (8" height)', 'Large (10" height)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M25 75L50 25L75 75z" stroke-width="3" fill="currentColor" fill-opacity="0.06"/><path d="M37 55h26" stroke-dasharray="3 3"/><path d="M50 25v50" stroke-dasharray="2 2" stroke-opacity="0.3"/></svg>`
  },
  {
    id: 'MC-CPT01',
    title: 'Morecare CP Hip Stabilizer Harness',
    megaCategory: 'cp-kids',
    category: 'cp-therapy',
    categoryLabel: 'CP Therapy & Support',
    price: 7999,
    oldPrice: 9500,
    rating: 4.6,
    reviews: 67,
    desc: 'Neoprene hip stabilizer harness with adjustable straps. Provides gentle compression and proprioceptive input to improve hip alignment during gait training.',
    features: ['Medical-Grade Neoprene', 'Adjustable Compression', 'Easy On/Off Design', 'Machine Washable'],
    sizes: ['Toddler (waist 16-20")', 'Child (waist 20-26")', 'Youth (waist 26-32")'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><ellipse cx="50" cy="50" rx="28" ry="22" stroke-width="3" fill="currentColor" fill-opacity="0.05"/><path d="M32 35l18 15 18-15" stroke-width="2" stroke-linecap="round"/><path d="M32 65l18-15 18 15" stroke-width="2" stroke-linecap="round"/><circle cx="50" cy="50" r="4" fill="currentColor" fill-opacity="0.2"/></svg>`
  },
  {
    id: 'MC-CPT02',
    title: 'Morecare CP Hand & Wrist Splint',
    megaCategory: 'cp-kids',
    category: 'cp-therapy',
    categoryLabel: 'CP Therapy & Support',
    price: 2499,
    oldPrice: 3200,
    rating: 4.5,
    reviews: 156,
    desc: 'Pediatric resting hand splint with thumb abduction. Maintains functional hand position and prevents contractures during rest and sleep in spastic CP.',
    features: ['Thumb Abduction Bar', 'Padded Palmar Support', 'Breathable Mesh Lining', 'Adjustable Velcro Straps'],
    sizes: ['Infant (0-2 yrs)', 'Child (3-8 yrs)', 'Youth (9-14 yrs)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M30 55c0-20 8-35 20-40s20 5 20 25v20c0 10-8 18-20 18s-20-8-20-18z" stroke-width="3" fill="currentColor" fill-opacity="0.05"/><path d="M38 40l5-15M50 35v-18M58 38l3-14" stroke-linecap="round" stroke-width="2"/><path d="M35 55h30" stroke-dasharray="3 3"/></svg>`
  },
  {
    id: 'MC-CPT03',
    title: 'Morecare CP Therapy Activity Mat',
    megaCategory: 'cp-kids',
    category: 'cp-therapy',
    categoryLabel: 'CP Therapy & Support',
    price: 8999,
    oldPrice: 11000,
    rating: 4.8,
    reviews: 94,
    desc: 'Multi-surface therapy mat with positioning wedges and bolsters. Provides safe, padded surface for tummy time, rolling practice, and therapeutic exercises.',
    features: ['6cm High-Density Foam', 'Non-Slip PVC Base', 'Includes 2 Wedges + 1 Bolster', 'Easy-Clean Vinyl Surface'],
    sizes: ['Standard (120x90 cm)', 'Large (150x120 cm)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><rect x="15" y="40" width="70" height="35" rx="4" stroke-width="3" fill="currentColor" fill-opacity="0.06"/><path d="M20 45h60M20 55h60M20 65h60" stroke-dasharray="4 4" stroke-opacity="0.15"/><path d="M70 40L85 25h-20z" fill="currentColor" fill-opacity="0.1" stroke-width="2"/><ellipse cx="30" cy="32" rx="8" ry="5" stroke-width="2" fill="currentColor" fill-opacity="0.08"/></svg>`
  },

  /* ===================================================================
     MEGA-CATEGORY: SHOP FOR ADULTS (13 SKUs)
     =================================================================== */
  {
    id: 'MC-W01',
    title: 'Morecare Carbon X Electric Wheelchair',
    megaCategory: 'adults',
    category: 'wheelchair',
    categoryLabel: 'Electric Wheelchairs',
    price: 139999,
    oldPrice: 155000,
    rating: 4.9,
    reviews: 124,
    desc: 'Ultra-lightweight aerospace carbon fiber frame. One-click folding, dual brushless motors, smart electromagnetic braking, and intelligent joystick controller.',
    features: ['Aviation Grade Carbon Fiber', '14.2 kg Net Weight', '18 km Battery Range', 'Anti-tip Safety Wheels'],
    sizes: ['Standard Seat (18")', 'Wide Seat (20")'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="40" cy="70" r="18" stroke-width="4"/><circle cx="75" cy="70" r="10" stroke-width="3"/><rect x="25" y="30" width="30" height="25" rx="4" fill="currentColor" fill-opacity="0.06"/><path d="M25 45h35M40 70l20-30M30 20h25M75 70l-15-30" stroke-linecap="round"/></svg>`
  },
  {
    id: 'MC-W02',
    title: 'Morecare Transit Lite Manual Wheelchair',
    megaCategory: 'adults',
    category: 'wheelchair',
    categoryLabel: 'Manual Wheelchairs',
    price: 12500,
    oldPrice: 15000,
    rating: 4.6,
    reviews: 98,
    desc: 'Ultra-portable manual attendant wheelchair. Extremely lightweight, folds completely flat in seconds. Ideal for travel, doctor visits, and restaurant excursions.',
    features: ['Aerospace Aluminum Alloy', '8.9 kg Total Weight', 'Attendant Loop Brakes', 'Foldable Backrest & Footplates'],
    sizes: ['Standard (17" width)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="35" cy="65" r="15"/><circle cx="68" cy="65" r="8"/><path d="M20 25h15M35 25v40M35 45h30M65 45v20M25 45h20" stroke-linecap="round"/><rect x="30" y="42" width="10" height="5" fill="currentColor" fill-opacity="0.15"/></svg>`
  },
  {
    id: 'MC-W03',
    title: 'Morecare Heavy-Duty Bariatric Wheelchair',
    megaCategory: 'adults',
    category: 'wheelchair',
    categoryLabel: 'Bariatric Wheelchairs',
    price: 32999,
    oldPrice: 40000,
    rating: 4.7,
    reviews: 45,
    desc: 'Reinforced steel frame bariatric wheelchair supporting up to 200 kg. Extra-wide seat, heavy-duty casters, and reinforced cross-braces for maximum durability.',
    features: ['200 kg Weight Capacity', 'Reinforced Steel Frame', 'Extra-Wide 24" Seat', 'Heavy-Duty Mag Wheels'],
    sizes: ['Wide (22" seat)', 'Extra-Wide (24" seat)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="35" cy="68" r="18" stroke-width="4"/><circle cx="72" cy="68" r="10" stroke-width="3"/><rect x="20" y="25" width="35" height="28" rx="4" stroke-width="3" fill="currentColor" fill-opacity="0.06"/><path d="M20 42h38M35 68l22-30M25 18h28M72 68l-14-28" stroke-linecap="round" stroke-width="2.5"/></svg>`
  },
  {
    id: 'MC-C01',
    title: 'Morecare Ergo-Air Seat Cushion',
    megaCategory: 'adults',
    category: 'cushion',
    categoryLabel: 'Comfort Cushions',
    price: 4999,
    oldPrice: 5999,
    rating: 4.8,
    reviews: 342,
    desc: 'Advanced air-inflatable support with 36 interconnected contour cells. Promotes tailbone pressure relief, pelvic alignment, and prevents long-sitting sores.',
    features: ['Adjustable Inflation Valve', 'Anti-Slip Silica Base', 'Breathable Cool-Mesh Cover', 'Precision Hand Pump'],
    sizes: ['Standard (18" x 16")', 'Compact (16" x 16")'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><rect x="20" y="25" width="60" height="50" rx="8" stroke-width="3" fill="currentColor" fill-opacity="0.05"/><circle cx="35" cy="40" r="4" fill="currentColor" fill-opacity="0.15"/><circle cx="50" cy="40" r="4" fill="currentColor" fill-opacity="0.15"/><circle cx="65" cy="40" r="4" fill="currentColor" fill-opacity="0.15"/><circle cx="35" cy="55" r="4" fill="currentColor" fill-opacity="0.15"/><circle cx="50" cy="55" r="5" stroke-width="2"/><circle cx="65" cy="55" r="4" fill="currentColor" fill-opacity="0.15"/><circle cx="35" cy="65" r="4" fill="currentColor" fill-opacity="0.15"/><circle cx="50" cy="65" r="4" fill="currentColor" fill-opacity="0.15"/><circle cx="65" cy="65" r="4" fill="currentColor" fill-opacity="0.15"/></svg>`
  },
  {
    id: 'MC-C02',
    title: 'Morecare Memory Foam Coccyx Cushion',
    megaCategory: 'adults',
    category: 'cushion',
    categoryLabel: 'Comfort Cushions',
    price: 3499,
    oldPrice: 4500,
    rating: 4.7,
    reviews: 267,
    desc: 'U-shaped memory foam coccyx relief cushion. Ergonomic cut-out suspends the tailbone to eliminate direct pressure for sciatic and post-surgical comfort.',
    features: ['U-Shaped Coccyx Cut-out', 'High-Density Memory Foam', 'Velvet Zip Cover', 'Non-Slip Bottom Dots'],
    sizes: ['Standard (17" x 14")', 'Large (19" x 16")'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M20 35c0-6 5-10 12-10h36c7 0 12 4 12 10v30c0 6-5 10-12 10H50l-5 10-5-10H32c-7 0-12-4-12-10z" stroke-width="3" fill="currentColor" fill-opacity="0.05"/><path d="M45 75V65" stroke-linecap="round" stroke-width="2"/><ellipse cx="50" cy="50" rx="12" ry="10" stroke-dasharray="3 3"/></svg>`
  },
  {
    id: 'MC-C03',
    title: 'Morecare Lumbar Support Back Cushion',
    megaCategory: 'adults',
    category: 'cushion',
    categoryLabel: 'Comfort Cushions',
    price: 2799,
    oldPrice: 3500,
    rating: 4.6,
    reviews: 189,
    desc: 'Contoured lumbar back support with adjustable strap. Memory foam conforms to spinal curve for office chairs, car seats, and wheelchairs.',
    features: ['Ergonomic Spinal Curve', 'Adjustable Elastic Strap', 'Breathable 3D Mesh', 'Fits All Chair Types'],
    sizes: ['Standard (15" x 13")'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M25 20c0 0 5 30 25 30s25-30 25-30" stroke-width="3"/><path d="M25 20v60h50V20" stroke-width="2" fill="currentColor" fill-opacity="0.04"/><path d="M35 45c8-5 22-5 30 0" stroke-width="2" stroke-dasharray="3 3"/><path d="M50 25v50" stroke-dasharray="2 2" stroke-opacity="0.2"/></svg>`
  },
  {
    id: 'MC-I01',
    title: 'Morecare Cloud-Gel Orthotic Insoles',
    megaCategory: 'adults',
    category: 'insoles',
    categoryLabel: 'Foot Wellness',
    price: 1499,
    oldPrice: 1999,
    rating: 4.7,
    reviews: 580,
    desc: 'Physiotherapist-approved dual gel shoe inserts. Features targeted heel shock absorption, reinforced high-arch cradle, and dynamic alignment support.',
    features: ['Medical Grade PU Gel', 'Deep Heel Cradle', 'Arch Support Structure', 'Odor-Resistant Fabric'],
    sizes: ['Small (UK 4-6)', 'Medium (UK 7-9)', 'Large (UK 10-12)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M45 15c-10 20-5 35-15 50s5 20 20 20c15 0 20-10 20-25S55 35 45 15z" stroke-width="3" stroke-linecap="round" fill="currentColor" fill-opacity="0.04"/><circle cx="50" cy="70" r="6" stroke-dasharray="2 2"/><path d="M40 50c5 5 15 5 20 0"/></svg>`
  },
  {
    id: 'MC-I02',
    title: 'Morecare Arch-Active Sports Insoles',
    megaCategory: 'adults',
    category: 'insoles',
    categoryLabel: 'Foot Wellness',
    price: 1799,
    oldPrice: 2299,
    rating: 4.9,
    reviews: 112,
    desc: 'High-performance running and fitness orthotics. Semi-rigid plastic shell for structural support with forefoot gel padding for energy rebound.',
    features: ['Vibe-Guard Shock Shell', 'Aerated Forefoot Breathing', 'Heel Pad Cushioning', 'Moisture-Wicking Mesh'],
    sizes: ['Medium (UK 7-9)', 'Large (UK 10-12)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M40 10c-5 15-5 30-10 45s5 25 15 25 15-5 20-15-5-35-10-45-5-10-15-10z" stroke-width="3" fill="currentColor" fill-opacity="0.04"/><path d="M35 55c10 0 15 10 20 20M32 40h12" stroke-linecap="round"/></svg>`
  },
  {
    id: 'MC-I03',
    title: 'Morecare Plantar Fasciitis Gel Insoles',
    megaCategory: 'adults',
    category: 'insoles',
    categoryLabel: 'Foot Wellness',
    price: 1999,
    oldPrice: 2499,
    rating: 4.8,
    reviews: 234,
    desc: 'Therapeutic gel insoles targeting plantar fasciitis and heel spurs. Extra-thick heel zone with shock-absorbing honeycomb gel technology.',
    features: ['Honeycomb Gel Heel Zone', 'Full-Length Support', 'Metatarsal Pad Included', 'Trimmable to Size'],
    sizes: ['Small (UK 4-6)', 'Medium (UK 7-9)', 'Large (UK 10-12)'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M43 12c-8 18-4 32-14 48s6 22 18 22 18-8 18-24-6-30-10-42-4-8-12-4z" stroke-width="3" fill="currentColor" fill-opacity="0.04"/><circle cx="46" cy="72" r="8" stroke-dasharray="2 2"/><circle cx="46" cy="72" r="4" fill="currentColor" fill-opacity="0.12"/><path d="M38 45h16" stroke-linecap="round"/></svg>`
  },
  {
    id: 'MC-P01',
    title: 'Morecare Contoured Cervical Pillow',
    megaCategory: 'adults',
    category: 'pillow',
    categoryLabel: 'Neck & Sleep',
    price: 2999,
    oldPrice: 3999,
    rating: 4.8,
    reviews: 215,
    desc: 'Ergonomic neck support molded from premium slow-rebound memory foam. Unique wave shape matches cervical curve for morning neck and shoulder relief.',
    features: ['Premium Memory Foam', 'Contoured Neck Cradle', 'Side-Sleeper Zones', 'Washable Bamboo Cover'],
    sizes: ['Standard (23" x 14")', 'Queen (25" x 15")'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><rect x="15" y="30" width="70" height="40" rx="10" stroke-width="3" fill="currentColor" fill-opacity="0.05"/><path d="M15 50q17.5-10 35 0t35 0" stroke-width="2"/></svg>`
  },
  {
    id: 'MC-P02',
    title: 'Morecare Travel Neck Support Pillow',
    megaCategory: 'adults',
    category: 'pillow',
    categoryLabel: 'Neck & Sleep',
    price: 1499,
    oldPrice: 1999,
    rating: 4.5,
    reviews: 178,
    desc: 'U-shaped memory foam travel neck pillow with snap closure. 360° neck support for flights, car rides, and train journeys. Compresses to half its size.',
    features: ['360° Neck Support', 'Snap Button Closure', 'Compressible Design', 'Velour Removable Cover'],
    sizes: ['One Size Fits All'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M50 20c-22 0-30 15-30 30s8 25 20 25c5 0 8-3 10-8 2 5 5 8 10 8 12 0 20-10 20-25s-8-30-30-30z" stroke-width="3" fill="currentColor" fill-opacity="0.05"/><path d="M50 20v10" stroke-linecap="round" stroke-width="2"/></svg>`
  },
  {
    id: 'MC-P03',
    title: 'Morecare Ergonomic Knee Pillow',
    megaCategory: 'adults',
    category: 'pillow',
    categoryLabel: 'Neck & Sleep',
    price: 1299,
    oldPrice: 1799,
    rating: 4.6,
    reviews: 134,
    desc: 'Hourglass-shaped memory foam knee pillow for side sleepers. Aligns hips and spine, reduces knee friction, and relieves sciatic and lower back pressure.',
    features: ['Hourglass Contour Design', 'Cooling Gel Layer', 'Anti-Slip Surface', 'Hypoallergenic Cover'],
    sizes: ['Standard'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M30 25c0-5 8-8 20-8s20 3 20 8v50c0 5-8 8-20 8s-20-3-20-8z" stroke-width="3" fill="currentColor" fill-opacity="0.05"/><path d="M32 50c8-6 18-6 36 0" stroke-width="2"/><path d="M50 20v60" stroke-dasharray="3 3" stroke-opacity="0.2"/></svg>`
  },
  {
    id: 'MC-WA01',
    title: 'Morecare Foldable Walking Cane',
    megaCategory: 'adults',
    category: 'walking',
    categoryLabel: 'Walking Aids',
    price: 1999,
    oldPrice: 2499,
    rating: 4.7,
    reviews: 203,
    desc: 'Aluminum foldable walking cane with ergonomic T-handle. Folds into 4 sections for travel convenience. Height adjustable with rubber anti-slip tip.',
    features: ['4-Section Foldable Design', 'Ergonomic T-Handle', 'Height Adjustable (32"-37")', 'LED Flashlight Base'],
    sizes: ['Standard (32"-37")'],
    graphic: `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M35 15h20c3 0 5 2 5 5v0c0 3-2 5-5 5H50" stroke-width="3" stroke-linecap="round"/><path d="M50 20v60" stroke-width="3" stroke-linecap="round"/><circle cx="50" cy="85" r="5" stroke-width="2" fill="currentColor" fill-opacity="0.1"/><path d="M46 40h8M46 55h8" stroke-linecap="round" stroke-dasharray="2 2"/></svg>`
  }
];
